# Example config for docker-compose-stack-backup-restore
backup:
  prefix: dcsbr # required, prefix for all backup files
  formats: ["tar.gz", "zip"] # options: tar.gz, zip, zst, or multiple
  sources:
    - ~/docker/my-toolstack
    # - another/source/folder
  target: ~/backup
  password: rahreeJaGh5ootu8Ahpohng1shah5Ees # optional, for encryption
  max_backups: 10 # optional, default is 10. Maximum number of backup files to keep per stack/format