name: Docker Compose Backup & Restore CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths-ignore: []
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        include:
          - GOOS: linux
            GOARCH: amd64
            BIN_NAME: dcsbr_linux_amd64
          - GOOS: linux
            GOARCH: arm64
            BIN_NAME: dcsbr_linux_arm64
          - GOOS: windows
            GOARCH: amd64
            BIN_NAME: dcsbr_windows_amd64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build binary
        run: |
          mkdir -p bin
          GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -v -o bin/${{ matrix.BIN_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.BIN_NAME }}
          path: bin/${{ matrix.BIN_NAME }}
      - name: Upload binary to VirusTotal
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: bin/${{ matrix.BIN_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./bin
      - name: Set version from tag
        id: get_version
        run: |
          echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./bin/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
